repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Autocode formatter (black)
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        name: Format docstrings (docformatter)
  - repo: local
    hooks:
      - id: tests
        name: Run pytest
        entry: pipenv run pytest -v
        language: system
        require_serial: true
        pass_filenames: false
