version: '3'
# We use this docker-compose file for deployment on the GII servers.
# It requires a .env file (mostly, with POSTGRES credentials) at the root of the repo.
services:
    google_pathways_web_app:
      image: brighthive/google_pathways_web_app:latest
      depends_on:
        - postgres_service
      environment:
        - APP_ENV=PRODUCTION
        - SECRET_KEY=${SECRET_KEY}
        - PSQL_USER=${POSTGRES_USER}
        - PSQL_PASSWORD=${POSTGRES_PASSWORD}
        - PSQL_HOSTNAME=postgres_service
        - PSQL_PORT=5432
        - PSQL_DATABASE=pathways
        - BASE_URL=${BASE_URL}
      ports:
        - "8000:8000"
    postgres_service:
      image: postgres:12
      env_file: .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=pathways
      ports:
        - "10031:5432"
    nginx:
      image: nginx:1.15-alpine
      ports:
          - "443:443"
      volumes:
          - ./data/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
          - ./data/nginx:/etc/nginx/conf.d
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      restart: on-failure
