"""empty message

Revision ID: ce1f5692d751
Revises: 
Create Date: 2020-04-02 15:17:25.899365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce1f5692d751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathways_program',
    sa.Column('pathways_program', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('gs_row_identifier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('gs_row_identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pathways_program')
    # ### end Alembic commands ###
